### PR TITLE
Add additional resource to project_final_js.md

### PR DESCRIPTION
**Pull request by lujanfernaud**

### CODE REVIEW

**Comment by 105ron** [comment]
What about [this one](https://blog.heroku.com/a-rock-solid-modern-web-stack)?

**Comment by lujanfernaud** [comment]
Looks great to me.

**Comment by KevinMulhern** [comment]
Are we adding the resource that @105ron suggested in this PR as well?

**Comment by lujanfernaud** [comment]
Just added the Heroku guide that @105ron suggested.

**Comment by 105ron** [comment]
Thank you @lujanfernaud 🥇

**Comment by lujanfernaud** [comment]
Glad to be of help :)

**Pull request merged**
