### PR TITLE
Take out #3 under Additional Resources

### PR DESCRIPTION
**Pull request by li3097**
Its a duplicate of Assignment #1 -Elements Panel #1

### CODE REVIEW

**Comment by li3097** [comment]
Is this what you are asking for? https://microverse.pathwright.com/library/microverse-pre-course-work-317b43d3/74348/path/step/43429649/

**Comment by CouchofTomato** [comment]
Hi @li3097 

I can't view that as you need to be logged in. Microverse aren't affiliated with us but use our resources in their teaching. If this is a Microverse issue you need to take it up with them otherwise if you could explain further what you are trying to change and where the duplication is we can investigate.

**Comment by li3097** [comment]
@CouchofTomato Under Assignment #1 it has a link to Chrome DevTools Documentation https://developers.google.com/web/tools/chrome-devtools/ which has the Elements panel #1 link of Get Started with Viewing and Changing CSS and all the information about it. The #3 under Additional Resources has "this interactive" points to the Get Started with Viewing and Changing CSS which was already covered up under the Assignment #1 link which points to Chrome DevTools > Elements Panel > Get Started with Viewing and Changing CSS.

**Comment by mindovermiles262** [comment]
I think I understand what's happening here. In the WD101 course The section "JavaScript Basics" has "3. Developer Tools" and then a few lessons down from there (in the "Javascript Basics" section) there is a lesson "Developer Tools 2" which is pretty much saying the same thing as the first lesson.

I'll create an issue for this as I just re-aranged all of the repos.

Thanks for submitting this @li3097

**Pull request closed without merging**
