### PR TITLE
adds student solution

### PR DESCRIPTION
**Pull request by paullyFIRE**

### CODE REVIEW

**Comment by mindovermiles262** [comment]
Hey @paullyFIRE 
This looks really good.  However, I get an error when trying to play:

screenshot_2018-01-19_07-20-41

**Comment by paullyFIRE** [comment]
Thanks for letting me know, Andy.

What browser did you get the error in?

**Comment by mindovermiles262** [comment]
I was using Firefox Latest version

**Comment by paullyFIRE** [comment]
Awesome - fixed it.

I was using srcElement attribute of the button's event - which was available in Chrome, but not FF.
Switched it out to the currentTarget attribute to work across both.

Thanks again, @mindovermiles262.

**Pull request merged**
