### PR TITLE
Update final-project.md

### PR DESCRIPTION
**Pull request by AnjaliDeshwani**

### CODE REVIEW

**Comment by arun1595** [comment]
@AnjaliDeshwani Have you deployed your calculator project? In your submission, `View in browser` is missing a link.

Do you know how to make use of [Github pages](https://pages.github.com/)?

**Comment by arun1595** [comment]
@AnjaliDeshwani It is not mandatory but provides a way for you to share your projects with others.

You can find the instructions on how to use github pages to deploy your frontend projects [here](https://www.theodinproject.com/courses/web-development-101/lessons/html-css#viewing-your-project-on-the-web)

Let us know if you've any questions.

**Comment by AnjaliDeshwani** [comment]
Thank you so much sir.
I have made the required changes .
Much obliged:)

**Comment by arun1595** [comment]
@AnjaliDeshwani Good work!

Consider dropping by our [Javascript gitter channel](https://gitter.im/TheOdinProject/Javascript) to get feedback on your project. People there would love to find bugs in the calculator project :wink: 

And, you don't have to address me as 'Sir'. I am a learner, just like you :smile:

**Pull request merged**
